### ISSUE TITLE
usermod command not found

### ISSUE THREAD

**Issue by Rfvgyhn** [goofball222/murmur#1]
I'm trying to run with custom UID and GID but I get the following error on startup:

```
<docker-entrypoint> INFO - Setting custom murmur UID/GID: UID=1000, GID=1001
/usr/local/bin/docker-entrypoint.sh: line 92: usermod: command not found
```
Is there something special I need to do besides specifying PUID and PGID in my compose file?

```bash
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
```bash
Docker version 17.12.0-ce, build c97c6d6
```
```bash
"org.label-schema.build-date": "2018-03-29T22:49:23Z",
"org.label-schema.license": "Apache-2.0",
"org.label-schema.name": "Murmur Server",
"org.label-schema.schema-version": "1.0",
"org.label-schema.url": "https://github.com/goofball222/murmur",
"org.label-schema.vcs-ref": "91fddfa",
"org.label-schema.vcs-url": "https://github.com/goofball222/murmur.git",
"org.label-schema.vendor": "goofball222",
"org.label-schema.version": "1.2.19"

```

**Comment by goofball222** [comment]
Looks like Alpine doesn't include the shadow package by default, which means the usermod and groupmod binaries are missing. I normally build on Debian or Ubuntu base images which have those in the base, so I missed testing this. I'll add the shadow package to the install list in the Dockerfile and rebuild the images shortly.

**Comment by goofball222** [comment]
Latest build of either "latest" or "snapshot" should have this fixed and it should be fully functional going forward. I see where I missed adding the "shadow" package initially after finding that su-exec wasn't needed as murmur will drop privileges by itself.
