### ISSUE TITLE
How to user cli to add new user on sqlite

### ISSUE THREAD

**Issue by SonPham1602** [goofball222/murmur#11]
Hello thanks you for your project.
I have a question. How can I add new user to Sqlite. Using command line or create new row on database. Thanks you.
![image](https://user-images.githubusercontent.com/43876888/120452717-9a01a880-c3bc-11eb-9f97-48aff6745c27.png)

**Comment by goofball222** [comment]
Users should be added via the Mumble client logged into the server as the SuperUser or an admin account.
