### ISSUE TITLE
Update to 1.3.0

### ISSUE THREAD

**Issue by PsikoBlock** [goofball222/murmur#4]
Mumble 1.3.0 was released: https://github.com/mumble-voip/mumble/releases/tag/1.3.0

stable and rc tags should be updated and maybe a new release-1.3.0 tag should be created.

**Comment by goofball222** [comment]
9aa0ee12 updates stable to 1.3.0 - release tagged. Images should be built on Docker Hub/Cloud shortly.

rc/snapshot images will remain on the last versions they had until there are active new versions designated with those tags from Mumble dev.
