### ISSUE TITLE
How to set SuperUser password?

### ISSUE THREAD

**Issue by kylebjordahl** [goofball222/murmur#6]
I've tried providing `-supw MyPassword` in the `MURMUR_OPTS` environment variable, however the entrypoint script puts the supplied options at the beginning of the argument chain (presumably so that the ones provided in the script take precedence?) but this causes an error from murmur, as it requires that `-supw` is the last argument.

I'd be glad to create a PR to add an additional environment variable at the end of the chain if that's helpful, but if there's a better way, please let me know.

* OS/distribution version:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

 * Docker version:

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Labels from container:

```
                "org.label-schema.build-date": "2020-04-02T18:35:03Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "Murmur Server",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/murmur",
                "org.label-schema.vcs-ref": "9aa0ee1",
                "org.label-schema.vcs-url": "https://github.com/goofball222/murmur.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "1.3.0",
```

**Comment by DaniDipp** [comment]
I came here for the same problem.
While I didn't find a way to set the SuperUser password, here is how I got access to the auto-generated one:
```
docker logs murmur 2>&1 | grep Password
```

**Comment by goofball222** [comment]
@DaniDipp has the correct normal solution for this for a new DB startup: obtain the password from the murmur container logs at first run, and then connect using it in the client and change the superuser password from there.

I went ahead and added functionality to support specifying/resetting the superuser password via a new environment variable MURMUR_SUPW as well. Murmur will not fully start or accept connections with -supw in the command line. Use `-e MURMUR_SUPW="newpasswordhere"` once and then remove it from the container run command or compose file.
